config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  devise_for :authors
 

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  resources :authors
  resources :homes
  resources :customers
  resources :suppliers
  resources :books  do
    resources:reviews
  end
  resources :orders
  resources :books do
    resources :reviews, only: [:new, :create]
  end 
  root "homes#index"
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :books 
end
   

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :reviews

  has_many :book_orders
  has_many :orders, through: :book_orders  

  has_many :comments, dependent: :destroy

  has_many :book_deliveries
  has_many :deliveries, through: :book_deliveries
end

app/models/book_delivery.rb
class BookDelivery < ApplicationRecord
  	belongs_to :book
    belongs_to :delivery
  
  end
  

app/models/book_order.rb
class BookOrder < ApplicationRecord
  belongs_to :book
  belongs_to :order
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book
  belongs_to:customer
  validates :body, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many:comments
    has_many:deliveries
    has_many :reviews
    has_many :books
    has_many :orders
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :customer
  has_and_belongs_to_many :books, join_table: 'book_deliverys'

   enum :status, [:shipped, :being_packed, :complete, :cancelled]

  scope :created_before, ->(time) { where(created_at: ...time) }


  has_many :book_deliveries
  has_many :books, through: :book_deliveries
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer

  has_many :book_orders
  has_many :books, through: :book_orders
  enum :status, [:shipped, :being_packed, :complete, :cancelled]
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :delivery
  belongs_to :book
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customer
  belongs_to :book
end

app/models/supplier.rb
class Supplier < ApplicationRecord
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    before_action :authenticate_author!, except: [:show]
    def index
        @authors = Author.all
    end
    
    def show
        @author = Author.find(params[:id])
      end
      
    
    def new
        @author = Author.new
    end
    
    def create
        @author = Author.new(author_params)
    
        if @author.save
        redirect_to @author
        else
        render :new, status: :unprocessable_entity
        end
    end
    
    def edit
        @author = Author.find(params[:id])
    end
    
    def update
        @author = Author.find(params[:id])
    
        if @author.update(author_params)
        redirect_to @author
        else
        render :edit, status: :unprocessable_entity
        end
    end
    
    def destroy
        @author = Author.find(params[:id])
        @author.destroy
    
        redirect_to root_path, status: :see_other
    end
    
    private
        def author_params
        params.require(:author).permit(:first_name, :last_name, :title)
        end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/deliverys_helper.rb
module DeliverysHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/supplier_helper.rb
module SupplierHelper
end

app/views/authors/_form.html.erb
<%= form_with model:author do |form| %>
    <div>
      <%= form.label :first_name %><br>
      <%= form.text_field :first_name %>
    </div>
  
    <div>
      <%= form.label :last_name %><br>
      <%= form.text_field :last_name %>
    </div>
    <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>
  
  

app/views/authors/edit.html.erb
<h1>Edit Author</h1>

<%= render "form", author: @author %>

app/views/authors/index.html.erb
<h1>Authors</h1>

<ul>
  <% @authors.each do |author| %>
    <li>
     first_name:- <%= link_to author.first_name,author %>
    </li>
  <% end %>
</ul>
<%= link_to "New Author", new_author_path %><br>

app/views/authors/new.html.erb
<h1>New Author</h1>
<%= render "form", author: @author %>


app/views/authors/show.html.erb
<h1>First_name:<%= @author.first_name %></h1>

<div style="margin-top: 20px;">
  <h3>Last Name: <%= @author.last_name %></h3>
  <h3>Title: <%= @author.title %></h3>
</div>

<ul>
  <li><%= link_to "Edit", edit_author_path(@author) %></li>
  <li><%= link_to "Destroy", author_path(@author), data: {
  turbo_method: :delete,
  turbo_confirm: "Are you sure?"
} %></li>

</ul>

