config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  devise_for :authors
 

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  resources :authors
  resources :homes
  resources :customers
  resources :suppliers
  resources :books  do
    resources:reviews
  end
  resources :orders
  resources :books do
    resources :reviews, only: [:new, :create]
  end 
  root "homes#index"
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :books 
end
   

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :reviews

  has_many :book_orders
  has_many :orders, through: :book_orders  

  has_many :comments, dependent: :destroy

  has_many :book_deliveries
  has_many :deliveries, through: :book_deliveries
end

app/models/book_delivery.rb
class BookDelivery < ApplicationRecord
  	belongs_to :book
    belongs_to :delivery
  
  end
  

app/models/book_order.rb
class BookOrder < ApplicationRecord
  belongs_to :book
  belongs_to :order
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book
  belongs_to:customer
  validates :body, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many:comments
    has_many:deliveries
    has_many :reviews
    has_many :books
    has_many :orders
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :customer
  has_and_belongs_to_many :books, join_table: 'book_deliverys'

   enum :status, [:shipped, :being_packed, :complete, :cancelled]

  scope :created_before, ->(time) { where(created_at: ...time) }


  has_many :book_deliveries
  has_many :books, through: :book_deliveries
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer

  has_many :book_orders
  has_many :books, through: :book_orders
  enum :status, [:shipped, :being_packed, :complete, :cancelled]
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :delivery
  belongs_to :book
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customer
  belongs_to :book
end

app/models/supplier.rb
class Supplier < ApplicationRecord
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    if params[:sort] == 'title'
      # binding.break
      @books = Book.order(title: :desc)
    elsif params[:sort] == 'year'
      @books = Book.order(year_published: :asc)

    else
      @books = Book.all
    end
  end
  
  def show
    @book = Book.find(params[:id])
    @reviews = @book.reviews
    
  end
  
  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
  
    if @book.save
      redirect_to @book
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
  
    if @book.update(book_params)
      redirect_to @book
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
  
    redirect_to root_path, status: :see_other
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :year_published, :price, :author_id)
  end
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/deliverys_helper.rb
module DeliverysHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/supplier_helper.rb
module SupplierHelper
end

app/views/books/_form.html.erb
<%= form_with model: @book do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </div>
    
    <div class="field">
      <%= form.label :author_id %><br>
      <%= form.collection_select(:author_id, Author.all, :id, :first_name, prompt: true) %>
    </div>
    
    <div>
      <%= form.label :year_published %><br>
      <%= form.text_field :year_published %>
    </div>
    
    <div>
      <%= form.label :price %><br>
      <%= form.text_field :price %>
    </div>
    
    <div>
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render "form", book: @book %>

app/views/books/index.html.erb
<h1>Books</h1>

<ol>
  <% @books.each do |book| %>
    <li>
      <%= link_to book.title, book %>
    </li>
  <% end %>
</ol>
<%= link_to "New Book", new_book_path %><br>
<%= link_to "Sort by Price", books_path(sort: 'price') %><br>
<%= link_to "Sort by year", books_path(sort: 'year') %>
<h2>10 years old Books</h2>
  <ul>
 

<%= link_to "Sort by Title", books_path(sort: 'title') %><br/>
<%= link_to "Sort by Year", books_path(sort: 'year') %><br/>
<%= link_to "Sort by Price", books_path(sort: 'price') %><br/>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= render "form", book: @book %>

app/views/books/show.html.erb
<h2>Book Details</h2>
<h3>Title: <%= @book.title%></h3>
<h3>Author: <%= @book.author.first_name %></h3>

<h3>Year_published: <%= @book.year_published %></h3>
<h3>Price:₹<%= @book.price %></h3>

<ul>
  <li><%= link_to "Edit", edit_book_path(@book) %></li>
  <li><%= link_to "Destroy", book_path(@book), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<% if @customers.present? %>
  <ol>
    <% @customers.each do |customer| %>
      <li>Customer: <%= customer.first_name %></li>
    <% end %>
  </ol>
<% else %>
  <p>No customers available.</p>
<% end %>
<h4>Reviews:</h4>
<% @reviews.each do |review| %>
  <p><%= review.body %></p>
<% end %>

<%= link_to "Add Review", new_book_review_path(@book.id) %>