config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  devise_for :authors
 

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  resources :authors
  resources :homes
  resources :customers
  resources :suppliers
  resources :books  do
    resources:reviews
  end
  resources :orders
  resources :books do
    resources :reviews, only: [:new, :create]
  end 
  root "homes#index"
 
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :books 
end
   

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :reviews

  has_many :book_orders
  has_many :orders, through: :book_orders  

  has_many :comments, dependent: :destroy

  has_many :book_deliveries
  has_many :deliveries, through: :book_deliveries
end

app/models/book_delivery.rb
class BookDelivery < ApplicationRecord
  	belongs_to :book
    belongs_to :delivery
  
  end
  

app/models/book_order.rb
class BookOrder < ApplicationRecord
  belongs_to :book
  belongs_to :order
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book
  belongs_to:customer
  validates :body, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many:comments
    has_many:deliveries
    has_many :reviews
    has_many :books
    has_many :orders
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :customer
  has_and_belongs_to_many :books, join_table: 'book_deliverys'

   enum :status, [:shipped, :being_packed, :complete, :cancelled]

  scope :created_before, ->(time) { where(created_at: ...time) }


  has_many :book_deliveries
  has_many :books, through: :book_deliveries
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer

  has_many :book_orders
  has_many :books, through: :book_orders
  enum :status, [:shipped, :being_packed, :complete, :cancelled]
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :delivery
  belongs_to :book
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customer
  belongs_to :book
end

app/models/supplier.rb
class Supplier < ApplicationRecord
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
   def index
     if current_author
       @books = Book.all
     elsif current_customer
       @customer = current_customer
       @customer_books = @customer.books
     else
       @books = Book.all
     end
   end
 end
 

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/deliverys_helper.rb
module DeliverysHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/supplier_helper.rb
module SupplierHelper
end

app/views/homes/index.html.erb
<h1>Bookstore</h1>

<p>Sign in as:</p>
<% if customer_signed_in? %>
  <%= current_customer.first_name %>
  <%= link_to "Sign Out", destroy_customer_session_path, method: :delete, data: { turbo_method: :delete } %>
<% else %>
  <%= link_to "Author", new_author_session_path %> |
  <%= link_to "Customer", new_customer_session_path %>
<% end %>

<% if @current_author %>
  <p>Welcome, <%= @current_author.first_name %>!</p>
  <h2>Your Books</h2>
  <ul>
    <% @current_author.books.each do |book| %>
      <li>BookName: <%= link_to book.title, book_path(book) %><br>
      Author: <%= link_to book.author.first_name, author_path(book.author) %></li>
    <% end %>
    <%= link_to "New Book", new_book_path %>
  </ul>

<% else %>
  <p>No author logged in.</p>
<% end %>


<% if current_customer %>
  <p>Welcome, <%= current_customer.first_name   %>!</p>
  <h2>Customer Details</h2>
  Books: <%= link_to "View Books", books_path %><br>
  <ul>
    <% current_customer.reviews.each do |review| %>
      <li>
        Book: <%= link_to review.book.title, book_path(review.book) %><br>
        Customer: <%= link_to review.customer.first_name, customer_path(review.customer) %><br>
      </li>
    <% end %>
  </ul>
  <h2>Orders</h2>
  <ul>
    <% if current_customer.orders.any? %>
      <% current_customer.orders.each do |order| %>
        <li>
          Order ID: <%= order.id %><br>
          Date Submitted: <%= order.date_submitted %><br>
          Status: <%= order.status %><br>
        </li>
      <% end %>
    <% else %>
      <p>No orders available for this customer.</p>
    <% end %>
    <%= link_to "New Order", new_order_path %>
  </ul>
  <% if current_customer %>
    <%= link_to "Sign Out", destroy_customer_session_path, method: :delete, data: { turbo_method: :delete } %>
  <% end %>
<% end %>