config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  devise_for :authors
 

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  resources :authors
  resources :homes
  resources :customers
  resources :suppliers
  resources :books  do
    resources:reviews
  end
  resources :orders
  resources :books do
    resources :reviews, only: [:new, :create]
  end 
  root "homes#index"
 
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :books 
end
   

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :reviews

  has_many :book_orders
  has_many :orders, through: :book_orders  

  has_many :comments, dependent: :destroy

  has_many :book_deliveries
  has_many :deliveries, through: :book_deliveries
end

app/models/book_delivery.rb
class BookDelivery < ApplicationRecord
  	belongs_to :book
    belongs_to :delivery
  
  end
  

app/models/book_order.rb
class BookOrder < ApplicationRecord
  belongs_to :book
  belongs_to :order
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book
  belongs_to:customer
  validates :body, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many:comments
    has_many:deliveries
    has_many :reviews
    has_many :books
    has_many :orders
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :customer
  has_and_belongs_to_many :books, join_table: 'book_deliverys'

   enum :status, [:shipped, :being_packed, :complete, :cancelled]

  scope :created_before, ->(time) { where(created_at: ...time) }


  has_many :book_deliveries
  has_many :books, through: :book_deliveries
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer

  has_many :book_orders
  has_many :books, through: :book_orders
  enum :status, [:shipped, :being_packed, :complete, :cancelled]
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :delivery
  belongs_to :book
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customer
  belongs_to :book
end

app/models/supplier.rb
class Supplier < ApplicationRecord
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
      @reviews = Review.all 
    end
    
  def new
      @book = Book.find(params[:book_id])
      @review = @book.reviews.new
  end

  def create
      book = Book.find(params[:book_id])
    @review = book.reviews.create(review_params)

    if @review.save
      redirect_to book_path(book.id), notice: 'Review was successfully created.'
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:body, :customer_id,:book_id)
  end
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/deliverys_helper.rb
module DeliverysHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/supplier_helper.rb
module SupplierHelper
end

app/views/reviews/_form.html.erb
<%= form_with model: [book,review] do |form| %>

    <div class="field">
    <%= form.label :customer_id %><br>
    <%= form.collection_select(:customer_id, Customer.all, :id, :first_name,prompt: true) %>
  </div>

    <div class="field">
      <%= form.label :body %><br>
      <%= form.text_field :body %>
    </div>

  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

app/views/reviews/new.html.erb
<h3>New Review for <%= @book.title %></h3>
<%= render 'form', review: @review ,book:@book %>

app/views/reviews/show.html.erb
<h1>Review Details</h1>

<p><strong>Customer:</strong> <%= @review.customer.first_name %> <%= @review.customer.last_name %></p>
<p><strong>Body:</strong> <%= @review.body %></p>
<p><strong>Created At:</strong> <%= @review.created_at %></p>

<%= link_to 'Back to Reviews', reviews_path %>
<%= link_to 'Show Review', review_path(@book) %>
<%= link_to "Add Review", new_book_review_path(@book) %>
